-- CASO 1
create table recaudacion_bonos_medicos
as
select  (m.rut_med || ' ' || m.dv_run) as rut_medico, 
        (m.pnombre || ' ' || m.apaterno || ' ' || m.amaterno) as nombre_medico, 
        u.nombre as unidad_medica, 
        sum(b.costo) as total_recaudado
from medico m
inner join unidad_consulta u on u.uni_id = m.uni_id
inner join bono_consulta b on b.rut_med = m.rut_med
where m.car_id not in (100,500,600) and extract(year from b.fecha_bono) = extract(year from sysdate) - 1 
group by m.rut_med,  m.dv_run, m.pnombre, m.apaterno,  m.amaterno, u.nombre
order by total_recaudado

-- CASO 2

select 
        count(distinct b.id_bono) as cantidad_bonos, 
        sum(b.costo) as monto_perdida, 
        min(b.fecha_bono) as fecha_bono, 
        e.nombre as especialidad_medica,
        'COBRABLE' as estado_de_cobro
from bono_consulta b
inner join (
    select b.id_bono
    from bono_consulta b
    minus
    select p.id_bono
    from pagos p
) bnp on bnp.id_bono = b.id_bono
inner join especialidad_medica e on e.esp_id = b.esp_id
where extract(year from b.fecha_bono) >= extract(year from sysdate)-1
group by e.nombre
union all
select 
        count(distinct b.id_bono) as cantidad_bonos, 
        sum(b.costo) as monto_perdida, 
        min(b.fecha_bono) as fecha_bono, 
        e.nombre as especialidad_medica,
        'INCOBRABLE' as estado_de_cobro
from bono_consulta b
inner join (
    select b.id_bono
    from bono_consulta b
    minus
    select p.id_bono
    from pagos p
) bnp on bnp.id_bono = b.id_bono
inner join especialidad_medica e on e.esp_id = b.esp_id
where extract(year from b.fecha_bono) < extract(year from sysdate)-1
group by e.nombre
order by cantidad_bonos, monto_perdida desc

-- CASO 3. PASO 1

select 
    (p.pac_run || '-' || p.dv_run) as rut_paciente, 
    round(round(sysdate - p.fecha_nacimiento)/365) as edad,
    ts.descripcion as sistema_salud,
    count(b.id_bono)as cantidad_bonos,
    sum(nvl(b.costo,0)) as costo_total
from paciente p
left join bono_consulta b on b.pac_run = p.pac_run and extract(year from b.fecha_bono) = extract(year from sysdate)
inner join salud s on s.sal_id = p.sal_id
inner join sistema_salud ts on ts.tipo_sal_id = s.tipo_sal_id
where ts.tipo_sal_id in ('F','P','FA')
group by p.pac_run, p.dv_run, p.fecha_nacimiento, ts.descripcion    
having
    count(b.id_bono) <= (
        select round(avg((count(id_bono))))
        from bono_consulta 
        where extract(year from fecha_bono) = (extract(year from sysdate)-1)
        group by pac_run
    )
order by cantidad_bonos, edad desc

--CASO 3. PASO 2

Insert into CANT_BONOS_PACIENTES_ANNIO(ANNIO_CALCULO,PAC_RUN,DV_RUN,EDAD,SISTEMA_SALUD,CANTIDAD_BONOS,MONTO_TOTAL_BONOS) values (2024,4922881,'3',87,'FONASA',0,0);
Insert into CANT_BONOS_PACIENTES_ANNIO(ANNIO_CALCULO,PAC_RUN,DV_RUN,EDAD,SISTEMA_SALUD,CANTIDAD_BONOS,MONTO_TOTAL_BONOS) values (2024,3331075,'7',85,'FONASA',0,0);
Insert into CANT_BONOS_PACIENTES_ANNIO(ANNIO_CALCULO,PAC_RUN,DV_RUN,EDAD,SISTEMA_SALUD,CANTIDAD_BONOS,MONTO_TOTAL_BONOS) values (2024,14438381,'8',82,'FONASA',0,0);
Insert into CANT_BONOS_PACIENTES_ANNIO(ANNIO_CALCULO,PAC_RUN,DV_RUN,EDAD,SISTEMA_SALUD,CANTIDAD_BONOS,MONTO_TOTAL_BONOS) values (2024,12765836,'6',76,'FONASA',0,0);
Insert into CANT_BONOS_PACIENTES_ANNIO(ANNIO_CALCULO,PAC_RUN,DV_RUN,EDAD,SISTEMA_SALUD,CANTIDAD_BONOS,MONTO_TOTAL_BONOS) values (2024,8601391,'6',64,'FONASA',0,0);
Insert into CANT_BONOS_PACIENTES_ANNIO(ANNIO_CALCULO,PAC_RUN,DV_RUN,EDAD,SISTEMA_SALUD,CANTIDAD_BONOS,MONTO_TOTAL_BONOS) values (2024,3632537,'2',60,'FONASA',0,0);
Insert into CANT_BONOS_PACIENTES_ANNIO(ANNIO_CALCULO,PAC_RUN,DV_RUN,EDAD,SISTEMA_SALUD,CANTIDAD_BONOS,MONTO_TOTAL_BONOS) values (2024,5537553,'4',56,'FONASA',0,0);
Insert into CANT_BONOS_PACIENTES_ANNIO(ANNIO_CALCULO,PAC_RUN,DV_RUN,EDAD,SISTEMA_SALUD,CANTIDAD_BONOS,MONTO_TOTAL_BONOS) values (2024,6845014,'4',47,'FONASA',0,0);
Insert into CANT_BONOS_PACIENTES_ANNIO(ANNIO_CALCULO,PAC_RUN,DV_RUN,EDAD,SISTEMA_SALUD,CANTIDAD_BONOS,MONTO_TOTAL_BONOS) values (2024,3066256,'3',38,'Fuerzas Armadas',0,0);
Insert into CANT_BONOS_PACIENTES_ANNIO(ANNIO_CALCULO,PAC_RUN,DV_RUN,EDAD,SISTEMA_SALUD,CANTIDAD_BONOS,MONTO_TOTAL_BONOS) values (2024,5117349,'K',37,'FONASA',0,0);
Insert into CANT_BONOS_PACIENTES_ANNIO(ANNIO_CALCULO,PAC_RUN,DV_RUN,EDAD,SISTEMA_SALUD,CANTIDAD_BONOS,MONTO_TOTAL_BONOS) values (2024,4389745,'4',35,'FONASA',0,0);
Insert into CANT_BONOS_PACIENTES_ANNIO(ANNIO_CALCULO,PAC_RUN,DV_RUN,EDAD,SISTEMA_SALUD,CANTIDAD_BONOS,MONTO_TOTAL_BONOS) values (2024,9073794,'5',21,'Fuerzas Armadas',0,0);
Insert into CANT_BONOS_PACIENTES_ANNIO(ANNIO_CALCULO,PAC_RUN,DV_RUN,EDAD,SISTEMA_SALUD,CANTIDAD_BONOS,MONTO_TOTAL_BONOS) values (2024,6626326,'6',88,'FONASA',1,28135);
Insert into CANT_BONOS_PACIENTES_ANNIO(ANNIO_CALCULO,PAC_RUN,DV_RUN,EDAD,SISTEMA_SALUD,CANTIDAD_BONOS,MONTO_TOTAL_BONOS) values (2024,5628094,'4',83,'FONASA',1,14343);
Insert into CANT_BONOS_PACIENTES_ANNIO(ANNIO_CALCULO,PAC_RUN,DV_RUN,EDAD,SISTEMA_SALUD,CANTIDAD_BONOS,MONTO_TOTAL_BONOS) values (2024,3754747,'6',79,'FONASA',1,25190);
Insert into CANT_BONOS_PACIENTES_ANNIO(ANNIO_CALCULO,PAC_RUN,DV_RUN,EDAD,SISTEMA_SALUD,CANTIDAD_BONOS,MONTO_TOTAL_BONOS) values (2024,3795697,'K',77,'FONASA',1,18846);
Insert into CANT_BONOS_PACIENTES_ANNIO(ANNIO_CALCULO,PAC_RUN,DV_RUN,EDAD,SISTEMA_SALUD,CANTIDAD_BONOS,MONTO_TOTAL_BONOS) values (2024,7800257,'3',74,'FONASA',1,23874);
Insert into CANT_BONOS_PACIENTES_ANNIO(ANNIO_CALCULO,PAC_RUN,DV_RUN,EDAD,SISTEMA_SALUD,CANTIDAD_BONOS,MONTO_TOTAL_BONOS) values (2024,5348333,'K',72,'FONASA',1,3634);
Insert into CANT_BONOS_PACIENTES_ANNIO(ANNIO_CALCULO,PAC_RUN,DV_RUN,EDAD,SISTEMA_SALUD,CANTIDAD_BONOS,MONTO_TOTAL_BONOS) values (2024,6407635,'3',66,'FONASA',1,15798);
Insert into CANT_BONOS_PACIENTES_ANNIO(ANNIO_CALCULO,PAC_RUN,DV_RUN,EDAD,SISTEMA_SALUD,CANTIDAD_BONOS,MONTO_TOTAL_BONOS) values (2024,7599430,'3',65,'FONASA',1,14582);
Insert into CANT_BONOS_PACIENTES_ANNIO(ANNIO_CALCULO,PAC_RUN,DV_RUN,EDAD,SISTEMA_SALUD,CANTIDAD_BONOS,MONTO_TOTAL_BONOS) values (2024,5932711,'9',48,'FONASA',1,19456);
Insert into CANT_BONOS_PACIENTES_ANNIO(ANNIO_CALCULO,PAC_RUN,DV_RUN,EDAD,SISTEMA_SALUD,CANTIDAD_BONOS,MONTO_TOTAL_BONOS) values (2024,3385116,'2',44,'FONASA',1,25826);
Insert into CANT_BONOS_PACIENTES_ANNIO(ANNIO_CALCULO,PAC_RUN,DV_RUN,EDAD,SISTEMA_SALUD,CANTIDAD_BONOS,MONTO_TOTAL_BONOS) values (2024,6340382,'2',42,'FONASA',1,11493);
Insert into CANT_BONOS_PACIENTES_ANNIO(ANNIO_CALCULO,PAC_RUN,DV_RUN,EDAD,SISTEMA_SALUD,CANTIDAD_BONOS,MONTO_TOTAL_BONOS) values (2024,10066612,'K',34,'FONASA',1,12739);
Insert into CANT_BONOS_PACIENTES_ANNIO(ANNIO_CALCULO,PAC_RUN,DV_RUN,EDAD,SISTEMA_SALUD,CANTIDAD_BONOS,MONTO_TOTAL_BONOS) values (2024,4603482,'1',31,'FONASA',1,34336);
Insert into CANT_BONOS_PACIENTES_ANNIO(ANNIO_CALCULO,PAC_RUN,DV_RUN,EDAD,SISTEMA_SALUD,CANTIDAD_BONOS,MONTO_TOTAL_BONOS) values (2024,7283959,'5',22,'FONASA',1,24393);
Insert into CANT_BONOS_PACIENTES_ANNIO(ANNIO_CALCULO,PAC_RUN,DV_RUN,EDAD,SISTEMA_SALUD,CANTIDAD_BONOS,MONTO_TOTAL_BONOS) values (2024,10726792,'1',15,'Fuerzas Armadas',1,61799);
Insert into CANT_BONOS_PACIENTES_ANNIO(ANNIO_CALCULO,PAC_RUN,DV_RUN,EDAD,SISTEMA_SALUD,CANTIDAD_BONOS,MONTO_TOTAL_BONOS) values (2024,5649139,'2',15,'FONASA',1,15944);
Insert into CANT_BONOS_PACIENTES_ANNIO(ANNIO_CALCULO,PAC_RUN,DV_RUN,EDAD,SISTEMA_SALUD,CANTIDAD_BONOS,MONTO_TOTAL_BONOS) values (2024,2576808,'6',8,'FONASA',1,33295);
Insert into CANT_BONOS_PACIENTES_ANNIO(ANNIO_CALCULO,PAC_RUN,DV_RUN,EDAD,SISTEMA_SALUD,CANTIDAD_BONOS,MONTO_TOTAL_BONOS) values (2024,6239390,'4',88,'FONASA',2,21567);
Insert into CANT_BONOS_PACIENTES_ANNIO(ANNIO_CALCULO,PAC_RUN,DV_RUN,EDAD,SISTEMA_SALUD,CANTIDAD_BONOS,MONTO_TOTAL_BONOS) values (2024,5455736,'1',85,'FONASA',2,37122);
Insert into CANT_BONOS_PACIENTES_ANNIO(ANNIO_CALCULO,PAC_RUN,DV_RUN,EDAD,SISTEMA_SALUD,CANTIDAD_BONOS,MONTO_TOTAL_BONOS) values (2024,1105913,'9',85,'FONASA',2,55731);
Insert into CANT_BONOS_PACIENTES_ANNIO(ANNIO_CALCULO,PAC_RUN,DV_RUN,EDAD,SISTEMA_SALUD,CANTIDAD_BONOS,MONTO_TOTAL_BONOS) values (2024,3911077,'6',84,'FONASA',2,40415);
Insert into CANT_BONOS_PACIENTES_ANNIO(ANNIO_CALCULO,PAC_RUN,DV_RUN,EDAD,SISTEMA_SALUD,CANTIDAD_BONOS,MONTO_TOTAL_BONOS) values (2024,12765873,'0',79,'FONASA',2,58000);
Insert into CANT_BONOS_PACIENTES_ANNIO(ANNIO_CALCULO,PAC_RUN,DV_RUN,EDAD,SISTEMA_SALUD,CANTIDAD_BONOS,MONTO_TOTAL_BONOS) values (2024,8918609,'9',75,'FONASA',2,33242);
Insert into CANT_BONOS_PACIENTES_ANNIO(ANNIO_CALCULO,PAC_RUN,DV_RUN,EDAD,SISTEMA_SALUD,CANTIDAD_BONOS,MONTO_TOTAL_BONOS) values (2024,8484348,'2',74,'FONASA',2,27990);
Insert into CANT_BONOS_PACIENTES_ANNIO(ANNIO_CALCULO,PAC_RUN,DV_RUN,EDAD,SISTEMA_SALUD,CANTIDAD_BONOS,MONTO_TOTAL_BONOS) values (2024,4410442,'3',58,'FONASA',2,63032);
Insert into CANT_BONOS_PACIENTES_ANNIO(ANNIO_CALCULO,PAC_RUN,DV_RUN,EDAD,SISTEMA_SALUD,CANTIDAD_BONOS,MONTO_TOTAL_BONOS) values (2024,5738855,'2',46,'FONASA',2,15581);
Insert into CANT_BONOS_PACIENTES_ANNIO(ANNIO_CALCULO,PAC_RUN,DV_RUN,EDAD,SISTEMA_SALUD,CANTIDAD_BONOS,MONTO_TOTAL_BONOS) values (2024,6110507,'7',40,'FONASA',2,15324);
Insert into CANT_BONOS_PACIENTES_ANNIO(ANNIO_CALCULO,PAC_RUN,DV_RUN,EDAD,SISTEMA_SALUD,CANTIDAD_BONOS,MONTO_TOTAL_BONOS) values (2024,4884829,'K',31,'Fuerzas Armadas',2,33548);
Insert into CANT_BONOS_PACIENTES_ANNIO(ANNIO_CALCULO,PAC_RUN,DV_RUN,EDAD,SISTEMA_SALUD,CANTIDAD_BONOS,MONTO_TOTAL_BONOS) values (2024,13770506,'0',9,'FONASA',2,24103);
Insert into CANT_BONOS_PACIENTES_ANNIO(ANNIO_CALCULO,PAC_RUN,DV_RUN,EDAD,SISTEMA_SALUD,CANTIDAD_BONOS,MONTO_TOTAL_BONOS) values (2024,15494012,'K',8,'FONASA',2,61028);
Insert into CANT_BONOS_PACIENTES_ANNIO(ANNIO_CALCULO,PAC_RUN,DV_RUN,EDAD,SISTEMA_SALUD,CANTIDAD_BONOS,MONTO_TOTAL_BONOS) values (2024,6215470,'5',4,'Fuerzas Armadas',2,54112);